name: Release

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm ci
            - run: npm test
            - run: npx semantic-release
              name: Create Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - run: npm publish
              name: Publish to NPM
              env:
                  npm_config_registry: https://registry.npmjs.org/
                  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

            - run: npm publish
              name: Publish to GitHub Packages
              env:
                  npm_config_registry: https://npm.pkg.github.com/
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
